# Translations for french
#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice, 
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice, 
#      this list of conditions and the following disclaimer in the documentation 
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors 
#      may be used to endorse or promote products derived from this software 
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# Adolfo Gómez <dkmaster at dkmon dot com>, 2012.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-11-20 04:05+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"

#: REST/methods/authenticators.py:80
msgid "Current authenticators"
msgstr "Authentificateurs actuels"

#: REST/methods/authenticators.py:82 REST/methods/networks.py:68
#: REST/methods/osmanagers.py:71 REST/methods/providers.py:69
#: REST/methods/transports.py:71 REST/methods/users.py:77
msgid "Name"
msgstr "Nom"

#: REST/methods/authenticators.py:83 REST/methods/osmanagers.py:72
#: REST/methods/providers.py:70 REST/methods/transports.py:72
#: REST/methods/users.py:78
msgid "Comments"
msgstr "Commentaires"

#: REST/methods/authenticators.py:84
msgid "Users"
msgstr "Utilisateurs"

#: REST/methods/networks.py:66
msgid "Current Networks"
msgstr "Réseaux actuels"

#: REST/methods/networks.py:69 templates/uds/index.html:79
#: templates/uds/html5/index.html:127
msgid "Networks"
msgstr "Réseaux"

#: REST/methods/networks.py:70 REST/methods/osmanagers.py:73
#: REST/methods/transports.py:73
msgid "Used by"
msgstr "Utilisé par"

#: REST/methods/osmanagers.py:69
msgid "Current OS Managers"
msgstr "Dirigeants de OS actuels"

#: REST/methods/providers.py:67
msgid "Current service providers"
msgstr "Fournisseurs de services actuels"

#: REST/methods/providers.py:71 templates/uds/index.html:51
#: templates/uds/html5/index.html:68
msgid "Services"
msgstr "Services"

#: REST/methods/transports.py:69
msgid "Current Transports"
msgstr "Transports actuels"

#: REST/methods/users.py:70
#, python-brace-format
msgid "Users of {0}"
msgstr "Utilisateurs de {0}"

#: REST/methods/users.py:72
msgid "Current users"
msgstr "Utilisateurs actuels"

#: REST/methods/users.py:76
msgid "User Id"
msgstr "Id de l'utilisateur"

#: REST/methods/users.py:79
msgid "state"
msgstr "État"

#: REST/methods/users.py:80
msgid "Last access"
msgstr "Dernier accès"

#: admin/views.py:55 admin/views.py:63 admin/views.py:77 web/views.py:422
msgid "Forbidden"
msgstr "Interdit"

#: admin/views.py:70
msgid "requested a template that do not exists"
msgstr "demandé un modèle qui ne sont pas existe"

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
#: auths/EDirectory_enterprise/Authenticator.py:60
#: auths/RegexLdap/Authenticator.py:49 auths/SimpleLDAP/Authenticator.py:49
#: services/HyperV_enterprise/HyperVClusterProvider.py:89
#: services/HyperV_enterprise/HyperVProvider.py:81
#: services/OVirt/OVirtProvider.py:92
#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "Host"
msgstr "Serveur"

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
msgid "Active Directory Server IP or Hostname"
msgstr "Active Directory Server IP ou nom d'hôte"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid "Use SSL"
msgstr "Utiliser SSL"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
msgid "If checked, will use a ssl connection to Active Directory"
msgstr "Si cochée, utilise une connexion ssl vers Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
msgid "Compatibility"
msgstr "Compatibilité"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
msgid "Compatibility of AD connection (Usually windows 2000 and later)"
msgstr "Compatibilité de connexion AD (généralement windows 2000 et versions ultérieures)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Ldap User"
msgstr "Utilisateur LDAP"

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
msgid ""
"Username with read privileges on the base selected (use USER@DOMAIN.DOM form "
"for this)"
msgstr ""
"Nom d'utilisateur avec des privilèges de lecture sur la base sélectionnée (utilisation USER@DOMAIN.Forme de DOM "
"pour cela)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:34
#: auths/ActiveDirectory_enterprise/Authenticator.py:52
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/RegexLdap/Authenticator.py:76
#: auths/SimpleLDAP/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:77
#: core/auths/BaseAuthenticator.py:136
#: osmanagers/WindowsOsManager/WinDomainOsManager.py:34
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
#: services/HyperV_enterprise/HyperVClusterProvider.py:92
#: services/HyperV_enterprise/HyperVProvider.py:84
#: services/OVirt/OVirtProvider.py:94 services/Sample/SampleService.py:131
#: services/Vmware_enterprise/ServiceProviderVC.py:31
#: transports/HTML5RDP/HTML5RDP.py:65 transports/NX/NXTransport.py:62
#: transports/NX/TSNXTransport.py:67 transports/RDP/RDPTransport.py:60
#: transports/RDP/TSRDPTransport.py:64
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67 web/forms/LoginForm.py:70
msgid "Password"
msgstr "Mot de passe"

#: auths/ActiveDirectory_enterprise/Authenticator.py:34
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:53
msgid "Password of the ldap user"
msgstr "Mot de passe de l'utilisateur ldap"

#: auths/ActiveDirectory_enterprise/Authenticator.py:35
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
#: services/HyperV_enterprise/HyperVClusterProvider.py:93
#: services/HyperV_enterprise/HyperVProvider.py:85
#: services/OVirt/OVirtProvider.py:95
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout"
msgstr "Temporisation"

#: auths/ActiveDirectory_enterprise/Authenticator.py:35
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
msgid "Timeout in seconds of connection to LDAP"
msgstr "Délai en secondes de la connexion à LDAP"

#: auths/ActiveDirectory_enterprise/Authenticator.py:37
msgid "Active Directory Authenticator"
msgstr "Authentificateur de Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:39
msgid "Authenticate against Active Directory"
msgstr "S'authentifier sur Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:48
#: auths/EDirectory_enterprise/Authenticator.py:77
#: auths/RegexLdap/Authenticator.py:72 auths/SimpleLDAP/Authenticator.py:73
#: services/HyperV_enterprise/HyperVClusterProvider.py:91
#: services/HyperV_enterprise/HyperVProvider.py:83
#: services/OVirt/OVirtProvider.py:93
#: services/Vmware_enterprise/ServiceProviderVC.py:30
#: transports/HTML5RDP/HTML5RDP.py:64 transports/NX/NXTransport.py:61
#: transports/NX/TSNXTransport.py:66 transports/RDP/RDPTransport.py:59
#: transports/RDP/TSRDPTransport.py:63
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66 web/forms/LoginForm.py:69
msgid "Username"
msgstr "Nom d'utilisateur"

#: auths/ActiveDirectory_enterprise/Authenticator.py:50
#: auths/EDirectory_enterprise/Authenticator.py:79
#: auths/RegexLdap/Authenticator.py:74 auths/SAML_enterprise/SAML.py:114
#: auths/SimpleLDAP/Authenticator.py:75
msgid "Group"
msgstr "Groupe"

#: auths/ActiveDirectory_enterprise/Authenticator.py:67
#: auths/ActiveDirectory_enterprise/Authenticator.py:442
msgid "Must specify the username in the form USERNAME@DOMAIN.DOM"
msgstr "Doit spécifier le nom d'utilisateur sous la forme USERNAME@DOMAIN.DOM"

#: auths/ActiveDirectory_enterprise/Authenticator.py:164
#: auths/EDirectory_enterprise/Authenticator.py:123
#: auths/RegexLdap/Authenticator.py:226 auths/SimpleLDAP/Authenticator.py:158
msgid "Ldap connection error: "
msgstr "Erreur de connexion LDAP : "

#: auths/ActiveDirectory_enterprise/Authenticator.py:344
#: auths/ActiveDirectory_enterprise/Authenticator.py:390
#: auths/EDirectory_enterprise/Authenticator.py:243
#: auths/EDirectory_enterprise/Authenticator.py:286
#: auths/RegexLdap/Authenticator.py:303 auths/RegexLdap/Authenticator.py:346
#: auths/SimpleLDAP/Authenticator.py:269 auths/SimpleLDAP/Authenticator.py:313
msgid "Username not found"
msgstr "Nom d'utilisateur introuvable"

#: auths/ActiveDirectory_enterprise/Authenticator.py:377
#: auths/SimpleLDAP/Authenticator.py:302
msgid "Group not found"
msgstr "Groupe introuvable"

#: auths/ActiveDirectory_enterprise/Authenticator.py:410
#: auths/ActiveDirectory_enterprise/Authenticator.py:428
#: auths/EDirectory_enterprise/Authenticator.py:303
#: auths/RegexLdap/Authenticator.py:367 auths/SimpleLDAP/Authenticator.py:328
#: auths/SimpleLDAP/Authenticator.py:342
msgid "Too many results, be more specific"
msgstr "Trop de résultats, être plus spécifique"

#: auths/ActiveDirectory_enterprise/Authenticator.py:451
msgid "Domain seems to be incorrect, please check it"
msgstr "Domaine semble être incorrect, veuillez bien consulter le"

#: auths/ActiveDirectory_enterprise/Authenticator.py:456
msgid "Ldap does not seem an Active Directory (do not have user objects)"
msgstr "LDAP ne semble pas un serveur Active Directory (n'ont pas les objets utilisateur)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:464
msgid "Ldap does not seem an Active Directory (no not have group objects)"
msgstr "LDAP ne semble pas un serveur Active Directory (ne pas ont des objets de groupe)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:472
msgid ""
"Ldap does not seem an Active Directory (do not have any user nor groups)"
msgstr ""
"LDAP ne semble pas un serveur Active Directory (n'ont pas l'utilisateur ou groupes)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:477
#: auths/EDirectory_enterprise/Authenticator.py:358
#: auths/RegexLdap/Authenticator.py:428 auths/SimpleLDAP/Authenticator.py:423
msgid "Connection params seem correct, test was succesfully executed"
msgstr ""
"Connexion params semblent correctes, le test a été correctement exécutée"

#: auths/EDirectory_enterprise/Authenticator.py:60
msgid "EDirectory Server IP or Hostname"
msgstr "Serveur EDirectory IP ou nom d'hôte"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
#: services/HyperV_enterprise/HyperVClusterProvider.py:90
#: services/HyperV_enterprise/HyperVProvider.py:82
#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "Port"
msgstr "Port"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
msgid "Ldap port (389 for non ssl, 636 for ssl normally"
msgstr "Port LDAP (389 non SSL, 636 pour ssl normalement"

#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid ""
"If checked, will use a ssl connection to ldap (if port is 389, will use in "
"fact port 636)"
msgstr ""
"Si cochée, utilise une connexion ssl à ldap (si le port est 389, utilisera "
"dans port de fait 636)"

#: auths/EDirectory_enterprise/Authenticator.py:63
msgid "Admin user"
msgstr "Utilisateur admin"

#: auths/EDirectory_enterprise/Authenticator.py:63
msgid "Username with read privileges on the eDirectory"
msgstr "Nom d'utilisateur avec des privilèges de lecture sur l'eDirectory"

#: auths/EDirectory_enterprise/Authenticator.py:67
msgid "eDirectory Authenticator"
msgstr "eDirectory authentificateur"

#: auths/EDirectory_enterprise/Authenticator.py:69
msgid "Authenticate against eDirectory"
msgstr "S'authentifier auprès d'eDirectory"

#: auths/EDirectory_enterprise/Authenticator.py:323
#: auths/RegexLdap/Authenticator.py:387 auths/SimpleLDAP/Authenticator.py:363
msgid "Ldap search base is incorrect"
msgstr "Base de recherche LDAP est incorrect"

#: auths/EDirectory_enterprise/Authenticator.py:328
#: auths/RegexLdap/Authenticator.py:392 auths/SimpleLDAP/Authenticator.py:368
msgid "Ldap user class seems to be incorrect (no user found by that class)"
msgstr ""
"Classe d'utilisateur LDAP semble incorrect (aucun utilisateur ne trouvé par "
"cette classe)"

#: auths/EDirectory_enterprise/Authenticator.py:336
#: auths/SimpleLDAP/Authenticator.py:384
msgid ""
"Ldap user id attribute seems to be incorrect (no user found by that "
"attribute)"
msgstr ""
"Attribut d'id utilisateur LDAP semble incorrect (aucun utilisateur ne "
"trouvée par qui attribut)"

#: auths/EDirectory_enterprise/Authenticator.py:344
msgid "Expected group attribute "
msgstr "Attribut groupe attendue "

#: auths/EDirectory_enterprise/Authenticator.py:353
msgid ""
"Ldap user class or user id attr is probably wrong (Ldap is an eDirectory?)"
msgstr ""
"LDAP user class ou utilisateur id attr est probablement faux (Ldap est un eDirectory?)"

#: auths/IP/Authenticator.py:48 auths/IP/Authenticator.py:50
msgid "IP Authenticator"
msgstr "Authentificateur IP"

#: auths/IP/Authenticator.py:54
msgid "IP"
msgstr "IP "

#: auths/IP/Authenticator.py:55
msgid "IP Range"
msgstr "Plage d'adresses IP"

#: auths/IP/Authenticator.py:92 auths/IP/Authenticator.py:95
#: auths/InternalDB/Authenticator.py:125
msgid "All seems fine in the authenticator."
msgstr "Tout semble fine dans l'authentificateur."

#: auths/InternalDB/Authenticator.py:47
msgid "Internal Database"
msgstr "Base de données interne"

#: auths/InternalDB/Authenticator.py:49
msgid "Internal dabasase authenticator. Doesn't uses external sources"
msgstr "Dabasase interne authentificateur. N'utilise des sources externes"

#: auths/InternalDB/Authenticator.py:59
msgid "Different user for each host"
msgstr "Verschiedene Benutzer für jeden host"

#: auths/InternalDB/Authenticator.py:59
msgid "If checked, each host will have a different user name"
msgstr "S'il est activé, chaque hôte aura un nom d'utilisateur différent"

#: auths/InternalDB/Authenticator.py:60
msgid "Reverse DNS"
msgstr "Reverse-DNS"

#: auths/InternalDB/Authenticator.py:60
msgid "If checked, the host will be reversed dns"
msgstr "S'il est activé, l'hôte sera dns inversée"

#: auths/InternalDB/Authenticator.py:122
msgid "Internal structures seems ok"
msgstr "Les structures internes semble ok"

#: auths/RegexLdap/Authenticator.py:49
msgid "Ldap Server Host"
msgstr "Hôte du serveur LDAP"

#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Username with read privileges on the base selected"
msgstr ""
"Nom d'utilisateur avec des privilèges de lecture sur la base sélectionnée"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Base"
msgstr "Base"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Common search base (used for \"users\" and \"groups\""
msgstr ""
"Recherche commune base (utilisé pour les « utilisateurs » et « groupes »"

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "User class"
msgstr "Classe utilisateur"

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "Class for LDAP users (normally posixAccount)"
msgstr "Classe pour les utilisateurs de LDAP (normalement posixAccount)"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "User Id Attr"
msgstr "Utilisateur Id Attr"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "Attribute that contains the user id"
msgstr "Attribut qui contient l'id utilisateur"

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "User Name Attr"
msgstr "Utilisateur nom Attr"

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "Attributes that contains the user name (list of comma separated values)"
msgstr ""
"Attributs qui contient le nom d'utilisateur (liste de valeurs séparées par "
"des virgules)"

#: auths/RegexLdap/Authenticator.py:59
msgid "Group Name Attr"
msgstr "Groupe nom Attr"

#: auths/RegexLdap/Authenticator.py:59
msgid "Attribute that contains the group name"
msgstr "Attribut qui contient le nom du groupe"

#: auths/RegexLdap/Authenticator.py:62
msgid "Regex LDAP Authenticator"
msgstr "Authentificateur LDAP Regex"

#: auths/RegexLdap/Authenticator.py:64
msgid "Regular Expressions LDAP authenticator"
msgstr "Authentificateur de LDAP d'Expressions régulière"

#: auths/RegexLdap/Authenticator.py:401
msgid ""
"Ldap user id attr is probably wrong (can't find any user with both "
"conditions)"
msgstr ""
"LDAP user id attr est probablement faux (ne peut pas trouver n'importe quel "
"utilisateur à la fois conditions)"

#: auths/RegexLdap/Authenticator.py:415 auths/SimpleLDAP/Authenticator.py:392
msgid ""
"Ldap group id attribute seems to be incorrect (no group found by that "
"attribute)"
msgstr ""
"Attribut d'id groupe LDAP semble incorrect (aucun groupe ne trouvée par qui "
"attribut)"

#: auths/SAML_enterprise/SAML.py:80
msgid "SAML Authenticator"
msgstr "SAML authentificateur"

#: auths/SAML_enterprise/SAML.py:92
msgid "SAML (v2.0) Authenticator"
msgstr "SAML (v2.0) authentificateur"

#: auths/SAML_enterprise/SAML.py:111 templates/uds/internal_page.html:28
msgid "User"
msgstr "Utilisateur"

#: auths/SAML_enterprise/SAML.py:120
msgid "Private key"
msgstr "Clé privée"

#: auths/SAML_enterprise/SAML.py:121
msgid ""
"Private key used for sign and encription, as generated in base 64 from "
"openssl"
msgstr ""
"Clé privée utilisée pour signe et encription, tel que généré en base 64 de "
"OpenSSL"

#: auths/SAML_enterprise/SAML.py:122
msgid "Certificate"
msgstr "Certificat"

#: auths/SAML_enterprise/SAML.py:123
msgid "Server certificate (public), , as generated in base 64 from openssl"
msgstr "Certificat serveur (public), comme généré en base 64 d'openssl"

#: auths/SAML_enterprise/SAML.py:124
msgid "IDP Metadata"
msgstr "Métadonnées de l'IDP"

#: auths/SAML_enterprise/SAML.py:125
msgid ""
"You can enter here the URL or the IDP metadata or the metadata itself (xml)"
msgstr ""
"Ici, vous pouvez entrer le URL ou les métadonnées d'IDP ou les métadonnées lui-même (xml)"

#: auths/SAML_enterprise/SAML.py:127
msgid "Entity ID"
msgstr "ID de l'entité"

#: auths/SAML_enterprise/SAML.py:128
msgid "ID of the SP. If left blank, this will be autogenerated from server URL"
msgstr "ID de la SP. Si laissé vide, ce sera généré automatiquement des URL du serveur"

#: auths/SAML_enterprise/SAML.py:130
msgid "User name attrs"
msgstr "Utilisateur nom attrs"

#: auths/SAML_enterprise/SAML.py:131
msgid "Fields from where to extract user name"
msgstr "Champs d'où extraire le nom d'utilisateur"

#: auths/SAML_enterprise/SAML.py:133
msgid "Group name attrs"
msgstr "Groupe nom attrs"

#: auths/SAML_enterprise/SAML.py:134
msgid "Fields from where to extract the groups"
msgstr "Champs d'où extraire les groupes"

#: auths/SAML_enterprise/SAML.py:136
msgid "Real name attrs"
msgstr "De son vrai nom attrs"

#: auths/SAML_enterprise/SAML.py:137
msgid "Fields from where to extract the real name"
msgstr "Champs d'où extraire le nom réel"

#: auths/SAML_enterprise/SAML.py:160
msgid ""
"Server certificate should be a valid PEM (PEM certificates starts with -----"
"BEGIN CERTIFICATE-----)"
msgstr ""
"Certificat de serveur doit être un PEM valide (PEM certificats commence par---"
"BEGIN CERTIFICATE---)"

#: auths/SAML_enterprise/SAML.py:165
msgid "Invalid server certificate. "
msgstr "Certificat de serveur non valide. "

#: auths/SAML_enterprise/SAML.py:168
msgid ""
"Private key should be a valid PEM (PEM private keys starts with -----BEGIN "
"RSA PRIVATE KEY-----"
msgstr ""
"Clé privée doit être un PEM valide (PEM clés privées commence par---BEGIN "
"RSA PRIVATE KEY---"

#: auths/SAML_enterprise/SAML.py:197
#, python-brace-format
msgid "Can't fetch url {0}: {1}"
msgstr "Impossible d'extraire url {0}: {1}"

#: auths/SAML_enterprise/SAML.py:208
msgid " (obtained from URL)"
msgstr " (obtenu à partir d'URL)"

#: auths/SAML_enterprise/SAML.py:209
msgid "XML do not seems valid for IDP Metadata "
msgstr "XML semble pas valide pour les métadonnées de l'IDP "

#: auths/SAML_enterprise/SAML.py:227
msgid "Can't access idp metadata"
msgstr "Ne peut pas accéder aux métadonnées de l'idp"

#: auths/Sample/SampleAuth.py:71
msgid "Sample Authenticator"
msgstr "Échantillon authentificateur"

#: auths/Sample/SampleAuth.py:83
msgid "Sample dummy authenticator"
msgstr "Authentificateur factice de l'échantillon"

#: auths/Sample/SampleAuth.py:102
msgid "Fake User"
msgstr "Faux utilisateur"

#: auths/Sample/SampleAuth.py:105
msgid "Fake Group"
msgstr "Faux groupe"

#: auths/Sample/SampleAuth.py:111
msgid "Groups"
msgstr "Groupes"

#: auths/Sample/SampleAuth.py:124
msgid "We need more that two items!"
msgstr "Nous avons besoin plus que deux points !"

#: auths/SimpleLDAP/Authenticator.py:49
msgid "Ldap Server IP or Hostname"
msgstr "IP du serveur LDAP ou nom d'hôte"

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Group class"
msgstr "Groupe classe"

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Class for LDAP groups (normally poxisGroup)"
msgstr "Classe pour les groupes LDAP (normalement poxisGroup)"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Group Id Attr"
msgstr "Groupe Id Attr"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Attribute that contains the group id"
msgstr "Attribut qui contient l'id de groupe"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Group membership attr"
msgstr "Groupe adhésion attr"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Attribute of the group that contains the users belonging to it"
msgstr "Attribut du groupe qui contient les utilisateurs appartenant à elle"

#: auths/SimpleLDAP/Authenticator.py:63
msgid "SimpleLDAP Authenticator"
msgstr "Authentificateur SimpleLDAP"

#: auths/SimpleLDAP/Authenticator.py:65
msgid "Simple LDAP authenticator"
msgstr "Simple authentificateur LDAP"

#: auths/SimpleLDAP/Authenticator.py:376
msgid "Ldap group class seems to be incorrect (no group found by that class)"
msgstr ""
"Classe de groupe LDAP semble incorrect (aucun groupe ne trouvée par cette "
"classe)"

#: auths/SimpleLDAP/Authenticator.py:401
msgid ""
"Ldap user class or user id attr is probably wrong (can't find any user with "
"both conditions)"
msgstr ""
"LDAP user utilisateur ou la classe id attr est probablement erroné (ne peut "
"pas trouver n'importe quel utilisateur avec les deux conditions)"

#: auths/SimpleLDAP/Authenticator.py:410
msgid ""
"Ldap group class or group id attr is probably wrong (can't find any group "
"with both conditions)"
msgstr ""
"LDAP groupe classe ou groupe id attr est probablement erroné (ne peut pas "
"trouver n'importe quel groupe avec les deux conditions)"

#: auths/SimpleLDAP/Authenticator.py:417
msgid "Can't locate any group with the membership attribute specified"
msgstr ""
"Ne peut pas localiser n'importe quel groupe avec l'attribut d'appartenance "
"spécifié"

#: core/BaseModule.py:197
msgid "No connection checking method is implemented."
msgstr "Aucun lien vérifier la méthode n'est implémentée."

#: core/BaseModule.py:266
msgid "No check method provided."
msgstr "Aucune méthode de vérification fournie."

#: core/auths/BaseAuthenticator.py:98 core/auths/BaseAuthenticator.py:110
msgid "Base Authenticator"
msgstr "Authentificateur de base"

#: core/auths/BaseAuthenticator.py:128
msgid "User name"
msgstr "Nom d'utilisateur"

#: core/auths/BaseAuthenticator.py:131
msgid "Group name"
msgstr "Nom du groupe"

#: core/auths/BaseAuthenticator.py:536
msgid "Users can't be created inside this authenticator"
msgstr ""
"Utilisateurs ne peut pas être créés à l'intérieur de cet authentificateur"

#: core/managers/PublicationManager.py:181
msgid ""
"Already publishing. Wait for previous publication to finish and try again"
msgstr ""
"Déjà la publication. Attendez une publication antérieure de terminer et "
"réessayez"

#: core/managers/PublicationManager.py:194
msgid "Can't cancel non running publication"
msgstr "Ne peut annuler la publication non courante"

#: core/managers/PublicationManager.py:212
msgid "Can't unpublish non usable publication"
msgstr "Ne peut annuler la publication publication non utilisable"

#: core/managers/PublicationManager.py:215
msgid "Can't unpublish publications with services in process"
msgstr ""
"Ne peut annuler la publication des publications avec services de processus"

#: core/managers/UserPrefsManager.py:257
msgid "Screen Size"
msgstr "Taille de l'écran"

#: core/managers/UserPrefsManager.py:261
msgid "Full Screen"
msgstr "Plein écran"

#: core/managers/UserPrefsManager.py:264
msgid "Screen colors"
msgstr "Couleurs de l'écran"

#: core/managers/UserPrefsManager.py:265
msgid "8 bits"
msgstr "8 bits"

#: core/managers/UserPrefsManager.py:266
msgid "16 bits"
msgstr "16 bits"

#: core/managers/UserPrefsManager.py:267
msgid "24 bits"
msgstr "24 bits"

#: core/managers/UserPrefsManager.py:268
msgid "32 bits"
msgstr "32 bits"

#: core/managers/UserServiceManager.py:320
msgid "Cancel requested for a non running operation, doing remove instead"
msgstr ""
"Annuler demandée pour une opération non en cours d'exécution, faire enlever "
"à la place"

#: core/managers/UserServiceManager.py:341
msgid "Can't remove a non active element"
msgstr "Impossible de supprimer un élément non actif"

#: core/managers/UserServiceManager.py:354
#, python-brace-format
msgid "Can't remove nor cancel {0} cause its states doesn't allows it"
msgstr "Ne peut pas supprimer ni annuler {0} cause ses États ne lui permet pas"

#: core/osmanagers/BaseOsManager.py:49
msgid "Base OS Manager"
msgstr "Gestionnaire d'OS de base"

#: core/osmanagers/BaseOsManager.py:51
msgid "Base Manager"
msgstr "Gestionnaire de base de"

#: core/services/BaseService.py:84 core/services/BaseService.py:96
msgid "Base Service"
msgstr "Service de base"

#: core/services/BaseService.py:117 core/services/BaseService.py:126
#: services/Sample/SampleService.py:92 services/Sample/SampleService.py:98
msgid "None"
msgstr "Aucun"

#: core/services/ClusteredService.py:39 core/services/ClusteredService.py:41
msgid "Base Clustered Service"
msgstr "Base en cluster Service"

#: core/transports/BaseTransport.py:147
msgid "Transport empty"
msgstr "Transport vide"

#: core/util/State.py:60
msgid "Active"
msgstr "Active"

#: core/util/State.py:60
msgid "Inactive"
msgstr "Inactif"

#: core/util/State.py:60
msgid "Blocked"
msgstr "Bloqué"

#: core/util/State.py:60
msgid "Waiting publication"
msgstr "Attente de publication"

#: core/util/State.py:61
msgid "In preparation"
msgstr "En préparation"

#: core/util/State.py:61
msgid "Valid"
msgstr "Valide"

#: core/util/State.py:62
msgid "Waiting for removal"
msgstr "Attente d'enlèvement"

#: core/util/State.py:62
msgid "Removing"
msgstr "Suppression"

#: core/util/State.py:62
msgid "Removed"
msgstr "Supprimé"

#: core/util/State.py:62
msgid "Canceled"
msgstr "Annulée"

#: core/util/State.py:63
msgid "Canceling"
msgstr "Annulation"

#: core/util/State.py:63 templates/uds/error.html:6
#: templates/uds/error.html.py:11 templates/uds/html5/error.html:4
#: templates/uds/html5/error.html.py:14
msgid "Error"
msgstr "Erreur"

#: core/util/State.py:63
msgid "Running"
msgstr "En cours d'exécution"

#: core/util/State.py:63
msgid "Finished"
msgstr "Fini"

#: core/util/State.py:63
msgid "Waiting execution"
msgstr "Exécution en attente"

#: core/util/State.py:64
msgid "Balancing"
msgstr "Équilibrage"

#: core/util/stats/counters.py:205
msgid "Assigned"
msgstr "Assignés"

#: core/util/stats/counters.py:206
msgid "In use"
msgstr "En cours d'utilisation"

#: core/util/stats/counters.py:207
msgid "Load"
msgstr "Charge"

#: core/util/stats/counters.py:208
msgid "Storage"
msgstr "Stockage"

#: dispatchers/wyse_enterprise/views.py:111
msgid "There are no authenticators available for login"
msgstr "Il n'existe aucun authentificateurs pour connexion"

#: dispatchers/wyse_enterprise/views.py:124
#, python-brace-format
msgid "The authenticator {0} is not usable"
msgstr "L'authentificateur {0} n'est pas utilisable"

#: dispatchers/wyse_enterprise/views.py:131 xmlrpc/auths/AdminAuth.py:168
msgid "Invalid credentials"
msgstr "Informations d'identification non valides"

#: dispatchers/wyse_enterprise/views.py:139
#, python-brace-format
msgid "The domain {0} does not exists"
msgstr "Le domaine {0} n'existe pas"

#: dispatchers/wyse_enterprise/views.py:200
msgid "No services available"
msgstr "Aucun service disponible"

#: dispatchers/wyse_enterprise/views.py:215
#: dispatchers/wyse_enterprise/views.py:309
msgid "Invalid session"
msgstr "Session invalide"

#: dispatchers/wyse_enterprise/views.py:219
#: dispatchers/wyse_enterprise/views.py:313
msgid "Invalid authorization"
msgstr "Autorisation non valide"

#: dispatchers/wyse_enterprise/views.py:230
#: dispatchers/wyse_enterprise/views.py:319
msgid "Invalid request"
msgstr "Requête non valide"

#: dispatchers/wyse_enterprise/views.py:233
#: dispatchers/wyse_enterprise/views.py:322
msgid "Invalid credentials used"
msgstr "Informations d'identification non valides utilisées"

#: dispatchers/wyse_enterprise/views.py:254
#: dispatchers/wyse_enterprise/views.py:257 web/errors.py:62
msgid "Service not found"
msgstr "Service introuvable"

#: dispatchers/wyse_enterprise/views.py:271 web/errors.py:61
msgid "Transport not found"
msgstr "Transport introuvable"

#: dispatchers/wyse_enterprise/views.py:275
#: dispatchers/wyse_enterprise/views.py:282
#: dispatchers/wyse_enterprise/views.py:287
#: templates/uds/service_not_ready.html:6
msgid "Service not ready at this moment. Please, try again in a while."
msgstr ""
"Le service n'est pas prêt à ce moment. S'il vous plaît, essayez à nouveau de "
"temps en temps."

#: osmanagers/LinuxOsManager/LinuxOsManager.py:45
msgid "Linux OS Manager"
msgstr "Gestionnaire de système d'exploitation Linux"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:47
msgid ""
"Os Manager to control linux virtual machines (basically renames machine and "
"notify state)"
msgstr ""
"Gestionnaire de l'os pour contrôler les machines virtuelles de linux "
"(essentiellement renomme machine et notifier l'État)"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:52
#: osmanagers/WindowsOsManager/WindowsOsManager.py:42
msgid "On Logout"
msgstr "Sur Logout"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:52
#: osmanagers/WindowsOsManager/WindowsOsManager.py:42
msgid "What to do when user logout from service"
msgstr "Que faire quand déconnexion de l'utilisateur du service"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:53
#: osmanagers/WindowsOsManager/WindowsOsManager.py:43
msgid "Keep service assigned"
msgstr "Garder les services affectés"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:54
#: osmanagers/WindowsOsManager/WindowsOsManager.py:44
msgid "Remove service"
msgstr "Retirer du service"

#: osmanagers/LinuxOsManager/__init__.py:43
msgid "UDS Actor for linux machines <b>(Requires python 2.6 or greater)"
msgstr ""
"Acteur de l'UDS pour linux machines <b>(nécessite le python 2.6 ou plus)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:26
msgid "Windows Domain OS Manager"
msgstr "Gestionnaire de système d'exploitation pour le domaine Windows"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:28
msgid ""
"Os Manager to control windows machines with domain. (Basically renames "
"machine)"
msgstr ""
"Os Manager pour contrôler les machines windows avec le domaine. "
"(Essentiellement renomme machine)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
#: transports/HTML5RDP/HTML5RDP.py:66 transports/RDP/RDPTransport.py:61
#: transports/RDP/TSRDPTransport.py:65
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid "Domain"
msgstr "Domaine"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
msgid "Domain to join machines to (use FQDN form, netbios name not allowed)"
msgstr ""
"Domaine de rejoindre machines pour (utiliser le formulaire nom de domaine "
"complet, nom netbios non autorisés)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:33
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "Account"
msgstr "Compte"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:33
msgid "Account with rights to add machines to domain"
msgstr "Compte avec droits d'ajouter des machines à domaine"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:34
msgid "Password of the account"
msgstr "Mot de passe du compte"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:35
msgid "OU"
msgstr "OU"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:35
msgid ""
"Organizational unit where to add machines in domain (check it before using "
"it)"
msgstr ""
"Unité organisationnelle où ajouter des machines dans le domaine (vérifier il "
"avant d'utiliser GTG"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:43
msgid "Must provide a domain!"
msgstr "Doit fournir un domaine !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:45
msgid "Must provide domain in FQDN"
msgstr "Remet le domaine dans le nom de domaine complet"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:47
msgid "Must provide an account to add machines to domain!"
msgstr "Doit fournir un compte pour ajouter des ordinateurs au domaine !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:49
msgid "DOM\\USER form is not allowed!"
msgstr "Formulaire DOM\\USER n'est pas autorisé !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:51
msgid "Must provide a password for the account!"
msgstr "Doit fournir un mot de passe pour le compte !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:145
#: osmanagers/WindowsOsManager/WinDomainOsManager.py:154
#, python-brace-format
msgid "Check error: {0}"
msgstr "Vérifiez l'erreur {0}"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:147
#, python-brace-format
msgid "Could not find server parameters (_ldap._tcp.{0} can'r be resolved)"
msgstr ""
"Paramètres du serveur est introuvable (_ldap._tcp. {0} can'r être résolu)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:157
msgid "Server check was successful"
msgstr "Contrôle serveur a été un succès"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:169
#, python-brace-format
msgid "Could not access AD using LDAP ({0})"
msgstr "Pas pu accéder à AD à l'aide de LDAP ({0})"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:181
#, python-brace-format
msgid "The default path {0} for computers was not found!!!"
msgstr "Le chemin par défaut {0} pour les ordinateurs n'a pas été trouvé !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:183
#, python-brace-format
msgid "The ou path {0} was not found!!!"
msgstr "Le chemin de l'unité d'organisation {0} n'a pas été trouvé !"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:185
#, python-brace-format
msgid "Could not check parameters (_ldap._tcp.{0} can'r be resolved)"
msgstr "Ne pouvait pas vérifier paramètres (_ldap._tcp. {0} can'r être résolu)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:190
msgid "All parameters seems to work fine."
msgstr "Tous les paramètres semble fonctionner très bien."

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:23
msgid "Windows Random Password OS Manager"
msgstr "Windows OS de mot de passe aléatoire Manager"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:25
msgid ""
"Os Manager to control windows machines, with user password set randomly."
msgstr ""
"Manager d'os à contrôle des machines windows, avec mot de passe utilisateur "
"défini au hasard."

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "User account to change password"
msgstr "Compte d'utilisateur pour modifier le mot de passe"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
msgid "Current (template) password of the user account"
msgstr "Mot de passe actuel (modèle) du compte d'utilisateur"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:39
msgid "Must provide an user account!!!"
msgstr "Doit fournir un compte d'utilisateur!!!"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:41
msgid "Must provide a password for the account!!!"
msgstr "Doit fournir un mot de passe du compte!!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:37
msgid "Windows Basic OS Manager"
msgstr "Gestionnaire de base de Windows OS"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:39
msgid ""
"Os Manager to control windows machines without domain. (Basically renames "
"machine)"
msgstr ""
"Os Manager pour contrôler les machines windows sans domaine. "
"(Essentiellement renomme machine)"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:53
msgid "Length must be numeric!!"
msgstr "La longueur doit être numérique!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:55
msgid "Length must be betwen 1 and six"
msgstr "La longueur doit être images 1 et six"

#: osmanagers/WindowsOsManager/__init__.py:25
msgid ""
"UDS Actor for windows machines <b>(Important!! Requires .net framework 3.5 "
"sp1)</b>"
msgstr ""
"Acteur de l'UDS pour machines windows <b>(Important!! Nécessite le .net "
"framework 3.5 SP1)</b>"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:51
msgid "HyperV Cluster Linked Clone (Experimental)"
msgstr "Cluster HyperV lié Clone (expérimental)"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:55
#: services/HyperV_enterprise/HyperVLinkedService.py:58
msgid "Hyper Services based on templates and differential disks (experimental)"
msgstr "Hyper Services basés sur des modèles et des disques différentiels (expérimentales)"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:72
#: services/HyperV_enterprise/HyperVLinkedService.py:75
#: services/OVirt/OVirtLinkedService.py:77
#: services/Vmware_enterprise/VCLinkedCloneService.py:72
msgid "Number of desired machines to keep running waiting for a user"
msgstr "Nombre de machines désirés de courir d'attente pour un utilisateur."

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:78
#: services/HyperV_enterprise/HyperVLinkedService.py:81
#: services/OVirt/OVirtLinkedService.py:83
#: services/Vmware_enterprise/VCLinkedCloneService.py:74
msgid "Number of desired machines to keep suspended waiting for use"
msgstr ""
"Nombre de machines désirés pour garder suspendu en attente pour utilisation"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:94
#: services/HyperV_enterprise/HyperVLinkedService.py:97
#: services/OVirt/OVirtLinkedService.py:99
#: services/Vmware_enterprise/VCLinkedCloneService.py:50
msgid "Base Machine"
msgstr "Machine de base"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:94
#: services/HyperV_enterprise/HyperVLinkedService.py:97
#: services/OVirt/OVirtLinkedService.py:99
msgid "Service base machine"
msgstr "Machine de base de service"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:95
#: services/HyperV_enterprise/HyperVLinkedService.py:98
#: services/Vmware_enterprise/VCLinkedCloneService.py:38
msgid "Network"
msgstr "Réseau"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:96
#: services/HyperV_enterprise/HyperVLinkedService.py:99
#: services/Vmware_enterprise/VCLinkedCloneService.py:39
msgid ""
"If more than 1 interface is found in machine, use one on this network as main"
msgstr ""
"Si plus d'une interface se trouve dans la machine, utiliser un sur ce réseau comme principal"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:98
#: services/HyperV_enterprise/HyperVLinkedService.py:101
#: services/OVirt/OVirtLinkedService.py:112
#: services/Vmware_enterprise/VCLinkedCloneService.py:51
msgid "Memory (Mb)"
msgstr "Mémoire (Mb)"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:99
#: services/HyperV_enterprise/HyperVLinkedService.py:102
#: services/Vmware_enterprise/VCLinkedCloneService.py:52
msgid "Memory for machines deployed from this service"
msgstr "Mémoire pour ordinateurs déployés de ce service"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:100
#: services/HyperV_enterprise/HyperVLinkedService.py:103
msgid "Datastore Drives"
msgstr "Lecteurs de magasin de données"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:101
#: services/HyperV_enterprise/HyperVLinkedService.py:104
msgid "Datastores where to put incrementals & publications"
msgstr "Entrepôts de données où mettre les sauvegardes incrémentielles & publications"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:102
#: services/HyperV_enterprise/HyperVLinkedService.py:105
#: services/OVirt/OVirtLinkedService.py:118
#: services/Vmware_enterprise/VCLinkedCloneService.py:55
msgid "Machine Names"
msgstr "Noms de machine"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:102
#: services/HyperV_enterprise/HyperVLinkedService.py:105
#: services/Vmware_enterprise/VCLinkedCloneService.py:55
msgid "Base name for clones from this machine"
msgstr "Nom de base des clones de cette machine"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:103
#: services/HyperV_enterprise/HyperVLinkedService.py:106
#: services/OVirt/OVirtLinkedService.py:119
#: services/Vmware_enterprise/VCLinkedCloneService.py:56
msgid "Name Length"
msgstr "Longueur du nom"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:104
#: services/HyperV_enterprise/HyperVLinkedService.py:107
#: services/OVirt/OVirtLinkedService.py:120
#: services/Vmware_enterprise/VCLinkedCloneService.py:57
msgid "Length of numeric part for the names of this machines (betwen 3 and 6"
msgstr ""
"Longueur de la partie numérique pour les noms de ces machines (images 3 et 6"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:116
#: services/HyperV_enterprise/HyperVLinkedService.py:119
#: services/OVirt/OVirtLinkedService.py:143
#: services/Vmware_enterprise/VCLinkedCloneService.py:95
msgid "The length of basename plus length must not be greater than 15"
msgstr ""
"La longueur du nom de base plus la longueur ne doit pas être supérieure à 15"

#: services/HyperV_enterprise/HyperVClusterLinkedService.py:118
#: services/HyperV_enterprise/HyperVLinkedService.py:121
#: services/OVirt/OVirtLinkedService.py:145
#: services/Vmware_enterprise/VCLinkedCloneService.py:97
msgid "The machine name can't be only numbers"
msgstr "Nom de l'ordinateur ne peut pas être uniquement des nombres"

#: services/HyperV_enterprise/HyperVClusterProvider.py:64
msgid "HyperV Cluster Provider"
msgstr "Fournisseur de Cluster HyperV"

#: services/HyperV_enterprise/HyperVClusterProvider.py:68
msgid "HyperV Cluster Service Provider"
msgstr "Fournisseur de Service de Cluster HyperV"

#: services/HyperV_enterprise/HyperVClusterProvider.py:89
#: services/HyperV_enterprise/HyperVProvider.py:81
msgid "HyperV Server IP or Hostname (must enable first WSMAN access)"
msgstr "HyperV serveur IP ou nom d'hôte (doit permettre l'accès WSMAN première)"

#: services/HyperV_enterprise/HyperVClusterProvider.py:90
#: services/HyperV_enterprise/HyperVProvider.py:82
msgid "WSMan Port (normally 5985)"
msgstr "WSMan Port (normalement 5985)"

#: services/HyperV_enterprise/HyperVClusterProvider.py:91
#: services/HyperV_enterprise/HyperVProvider.py:83
msgid "User with valid privileges on HyperV Server"
msgstr "Utilisateur avec des privilèges valides sur serveur HyperV"

#: services/HyperV_enterprise/HyperVClusterProvider.py:92
#: services/HyperV_enterprise/HyperVProvider.py:84
msgid "Password of the user of HyperV"
msgstr "Mot de passe de l'utilisateur de HyperV"

#: services/HyperV_enterprise/HyperVClusterProvider.py:93
#: services/HyperV_enterprise/HyperVProvider.py:85
msgid "Timeout in seconds of connection to HyperV"
msgstr "Délai d'attente en secondes de connexion pour HyperV"

#: services/HyperV_enterprise/HyperVClusterProvider.py:94
#: services/HyperV_enterprise/HyperVProvider.py:86
#: services/OVirt/OVirtProvider.py:96
#: services/Vmware_enterprise/ServiceProviderVC.py:33
msgid "Macs range"
msgstr "Gamme Mac"

#: services/HyperV_enterprise/HyperVClusterProvider.py:95
#: services/HyperV_enterprise/HyperVProvider.py:87
#: services/OVirt/OVirtProvider.py:97
msgid "Range of valids macs for created machines"
msgstr "Gamme de Mac valides pour les machines créés"

#: services/HyperV_enterprise/HyperVClusterProvider.py:132
msgid "The selected server is not a cluster"
msgstr "Le serveur sélectionné n'est pas un cluster"

#: services/HyperV_enterprise/HyperVClusterProvider.py:299
#: services/HyperV_enterprise/HyperVProvider.py:249
#: services/OVirt/OVirtProvider.py:399
msgid "Connection test successful"
msgstr "Test de connexion réussie"

#: services/HyperV_enterprise/HyperVClusterProvider.py:300
#: services/HyperV_enterprise/HyperVProvider.py:250
#: services/OVirt/OVirtProvider.py:400
#: services/Vmware_enterprise/ServiceProviderVC.py:120
msgid "Connection failed. Check connection params"
msgstr "Échec de la connexion. Vérifiez la connexion params"

#: services/HyperV_enterprise/HyperVClusterPublication.py:97
#: services/HyperV_enterprise/HyperVPublication.py:96
#: services/OVirt/OVirtPublication.py:85
#, python-brace-format
msgid "UDS pub for {0} at {1}"
msgstr "Pub UDS {0} sur {1}"

#: services/HyperV_enterprise/HyperVLinkedService.py:54
msgid "HyperV Linked Clone (Experimental)"
msgstr "HyperV Clone lié (expérimental)"

#: services/HyperV_enterprise/HyperVProvider.py:62
msgid "HyperV Platform Provider"
msgstr "Fournisseur de plates-formes HyperV"

#: services/HyperV_enterprise/HyperVProvider.py:66
msgid "HyperV platform service provider"
msgstr "Fournisseur de services de plate-forme HyperV"

#: services/OVirt/OVirtLinkedService.py:56
msgid "oVirt Linked Clone (Experimental)"
msgstr "oVirt Linked Clone (expérimental)"

#: services/OVirt/OVirtLinkedService.py:60
msgid "oVirt Services based on templates and COW (experimental)"
msgstr "oVirt Services basés sur les modèles et la vache (expérimentale)"

#: services/OVirt/OVirtLinkedService.py:100
msgid "Cluster"
msgstr "Cluster"

#: services/OVirt/OVirtLinkedService.py:106
msgid "Cluster to contain services"
msgstr "Cluster pour contenir les services"

#: services/OVirt/OVirtLinkedService.py:109
msgid "Datastore Domain"
msgstr "Domaine de magasin de données"

#: services/OVirt/OVirtLinkedService.py:110
msgid "Datastore domain where to publish and put incrementals"
msgstr ""
"Domaine de magasin de données où les publier et de mettre des sauvegardes "
"incrémentales"

#: services/OVirt/OVirtLinkedService.py:113
msgid "Memory assigned to machines"
msgstr "Mémoire attribuée aux machines"

#: services/OVirt/OVirtLinkedService.py:115
msgid "Memory Guaranteed (Mb)"
msgstr "Mémoire garantie (Mb)"

#: services/OVirt/OVirtLinkedService.py:116
msgid "Physical memory guaranteed to machines"
msgstr "Mémoire physique garantie aux machines"

#: services/OVirt/OVirtLinkedService.py:122
msgid "Display"
msgstr "Affichage"

#: services/OVirt/OVirtLinkedService.py:123
msgid "Display type (only for administration pourposses)"
msgstr "Type d'affichage (uniquement pour l'administration pourposses)"

#: services/OVirt/OVirtProvider.py:73
msgid "oVirt Platform Provider"
msgstr "oVirt fournisseur de plate-forme"

#: services/OVirt/OVirtProvider.py:77
msgid "oVirt platform service provider"
msgstr "fournisseur de services de plate-forme oVirt"

#: services/OVirt/OVirtProvider.py:92
msgid "oVirt Server IP or Hostname"
msgstr "oVirt serveur IP ou nom d'hôte"

#: services/OVirt/OVirtProvider.py:93
msgid "User with valid privileges on oVirt, (use \"user@domain\" form)"
msgstr ""
"Utilisateur avec des privilèges valides sur oVirt, (formulaire « user@domain "
"»)"

#: services/OVirt/OVirtProvider.py:94
msgid "Password of the user of oVirt"
msgstr "Mot de passe de l'utilisateur d'oVirt"

#: services/OVirt/OVirtProvider.py:95
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout in seconds of connection to VC"
msgstr "Délai en secondes de connexion à VC"

#: services/PhysicalMachines/IPMachineDeployed.py:57
msgid "IP "
msgstr "IP "

#: services/PhysicalMachines/IPMachinesService.py:46
msgid "List of IPS"
msgstr "Liste des IPS"

#: services/PhysicalMachines/IPMachinesService.py:49
msgid "Physical machines accesed by ip"
msgstr "Accesed de machines physiques par ip"

#: services/PhysicalMachines/IPMachinesService.py:51
msgid "This service provides access to POWERED-ON Machines by ip"
msgstr "Ce service permet d'accéder aux machines SOUS-TENSION par ip"

#: services/Sample/SampleProvider.py:68
msgid "Sample Provider"
msgstr "Exemple de fournisseur"

#: services/Sample/SampleProvider.py:72
msgid "Sample (and dummy) service provider"
msgstr "Fournisseur de services de l'échantillon (et factice)"

#: services/Sample/SampleProvider.py:92
msgid "Remote host"
msgstr "Hôte distant"

#: services/Sample/SampleProvider.py:93
msgid "This fields contains a remote host"
msgstr "Ce champs contient un hôte distant"

#: services/Sample/SampleProvider.py:99
msgid "Your pet's name"
msgstr "Nom de votre animal"

#: services/Sample/SampleProvider.py:100
msgid "If you like, write the name of your pet"
msgstr "Si vous le souhaitez, écrivez le nom de votre animal de compagnie"

#: services/Sample/SampleProvider.py:109
msgid "Age of Methuselah"
msgstr "Âge de Mathusalem"

#: services/Sample/SampleProvider.py:110
msgid "If you know it, please, tell me!!!"
msgstr "Si vous le savez, s'il vous plaît, dites-moi!!!"

#: services/Sample/SampleProvider.py:117
msgid "Is Methuselah still alive?"
msgstr "Mathusalem est encore en vie ?"

#: services/Sample/SampleProvider.py:118
msgid "If you fails, this will not get saved :-)"
msgstr "Si vous ne parvient pas, cela ne va pas être sauvé:-)"

#: services/Sample/SampleProvider.py:138
msgid "Methuselah is not alive!!! :-)"
msgstr "Mathusalem n'est pas vivant!!! :-)"

#: services/Sample/SampleProvider.py:178
msgid "Nothing tested, but all went fine.."
msgstr "Rien à l'épreuve, mais tout s'est bien passé..."

#: services/Sample/SamplePublication.py:195
msgid "Random integer was 9!!! :-)"
msgstr "Nombre entier aléatoire était 9!!! :-)"

#: services/Sample/SampleService.py:71
msgid "Sample Service One"
msgstr "Exemple un Service"

#: services/Sample/SampleService.py:75
msgid "Sample (and dummy) service ONE"
msgstr "Service de l'échantillon (et factice) un"

#: services/Sample/SampleService.py:118
msgid "Colour"
msgstr "Couleur"

#: services/Sample/SampleService.py:119
msgid "Colour of the field"
msgstr "Couleur du champ"

#: services/Sample/SampleService.py:132
msgid "Password for testing purposes"
msgstr "Mot de passe pour des fins de test"

#: services/Sample/SampleService.py:138
msgid "Services names"
msgstr "Noms de services"

#: services/Sample/SampleService.py:139
msgid "Base name for this user services"
msgstr "Nom de base pour les services de cet utilisateur"

#: services/Sample/SampleService.py:196
msgid "Sample Service Two"
msgstr "Exemple de Service deux"

#: services/Sample/SampleService.py:198
msgid "Sample (and dummy) service ONE+ONE"
msgstr "L'échantillon (et factice) service ONE + un"

#: services/Sample/SampleService.py:204
msgid "L1 cache for dummy elements"
msgstr "Cache L1 pour les éléments factices"

#: services/Sample/SampleService.py:206
msgid "L2 cache for dummy elements"
msgstr "Mémoire cache L2 de faux éléments"

#: services/Sample/SampleService.py:220
msgid "List of names"
msgstr "Liste des noms"

#: services/Vmware_enterprise/Helpers.py:72
msgid "Local"
msgstr "Local"

#: services/Vmware_enterprise/Helpers.py:74
msgid "Remote"
msgstr "Distance"

#: services/Vmware_enterprise/PublicationVC.py:37
msgid "Publication"
msgstr "Publication"

#: services/Vmware_enterprise/PublicationVC.py:38
#, python-brace-format
msgid "UDS Publication for {0} created at {1}"
msgstr "Publication UDS {0} créé à {1}"

#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "VMWare VC Server IP or Hostname"
msgstr "VMWare Server VC IP ou nom d'hôte"

#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "VMWare VC Server Port (usually 443)"
msgstr "Port du serveur VMWare VC (habituellement 443)"

#: services/Vmware_enterprise/ServiceProviderVC.py:30
msgid "User with valid privileges on VC"
msgstr "Utilisateur avec des privilèges valides sur VC"

#: services/Vmware_enterprise/ServiceProviderVC.py:31
msgid "Password of the user of the VC"
msgstr "Mot de passe de l'utilisateur de la CV"

#: services/Vmware_enterprise/ServiceProviderVC.py:34
msgid ""
"Range of valids macs for created machines. Must be inside "
"00:50:56:00:00:00-00:50:56:3F:FF:FF"
msgstr ""
"Gamme de valids Mac pour machines créées. Doit être à l'intérieur "
"00:50:56:00:00:00-00:50:56:3F:FF:FF"

#: services/Vmware_enterprise/ServiceProviderVC.py:39
msgid "VMWare Virtual Center Provider"
msgstr "VMWare Virtual Center fournisseur"

#: services/Vmware_enterprise/ServiceProviderVC.py:41
msgid "Provides connection to Virtual Center Services"
msgstr "Fournit la connexion à des Services de centre virtuel"

#: services/Vmware_enterprise/ServiceProviderVC.py:110
msgid "Error testing connection"
msgstr "Erreur de connexion test"

#: services/Vmware_enterprise/ServiceProviderVC.py:113
msgid "VmwareVC Provider: "
msgstr "VmwareVC fournisseur : "

#: services/Vmware_enterprise/ServiceProviderVC.py:119
msgid "Connection params ok"
msgstr "Connexion params ok"

#: services/Vmware_enterprise/VCLinkedCloneService.py:30
msgid "Datacenter"
msgstr "Datacenter"

#: services/Vmware_enterprise/VCLinkedCloneService.py:36
msgid "Datacenter containing base machine"
msgstr "Machine de base contenant Datacenter"

#: services/Vmware_enterprise/VCLinkedCloneService.py:40
msgid "Pub. Resource Pool"
msgstr "Pub. Liste des ressources"

#: services/Vmware_enterprise/VCLinkedCloneService.py:40
msgid "Resource Pool where deploy clones"
msgstr "Liste des ressources où déployer des clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:41
msgid "Clones Folder"
msgstr "Dossier de clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:41
msgid "Folder where deploy clones"
msgstr "Dossier où déployer des clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:42
msgid "Resource Pool"
msgstr "Liste des ressources"

#: services/Vmware_enterprise/VCLinkedCloneService.py:48
msgid "Resource Pool containing base machine"
msgstr "Machine de base contenant de ressource Pool"

#: services/Vmware_enterprise/VCLinkedCloneService.py:50
msgid "Base machine for this service"
msgstr "Machine de base pour ce service"

#: services/Vmware_enterprise/VCLinkedCloneService.py:53
msgid "Datastores"
msgstr "Entrepôts de données"

#: services/Vmware_enterprise/VCLinkedCloneService.py:54
msgid "Datastores where to put incrementals"
msgstr "Entrepôts de données où mettre des sauvegardes incrémentales"

#: services/Vmware_enterprise/VCLinkedCloneService.py:64
msgid "VMWare Linked clone base"
msgstr "Base de clone lié VMWare"

#: services/Vmware_enterprise/VCLinkedCloneService.py:66
msgid ""
"This service provides access to Linked Clones machines on a Virtual Center"
msgstr ""
"Ce service donne accès aux machines de Clones liés sur un Virtual Center"

#: templates/404.html:3 templates/500.html:3
msgid "Page not found"
msgstr "Page non trouvée"

#: templates/uds/base.html:7
msgid "UDS"
msgstr "UDS"

#: templates/uds/detectJava.html:6
msgid "Login redirection"
msgstr "Redirection de connexion"

#: templates/uds/detectJava.html:38 templates/uds/html5/detectJava.html:27
msgid "Go to main page"
msgstr "Aller à la page d'accueil"

#: templates/uds/downloads.html:8 templates/uds/html5/downloads.html:7
#: templates/uds/html5/snippets/navbar.html:41
#: templates/uds/snippets/admin_user.html:7
msgid "Downloads"
msgstr "Téléchargements"

#: templates/uds/downloads.html:11 templates/uds/html5/downloads.html:10
msgid ""
"This page contains a list of downloadables provided by different modules"
msgstr ""
"Cette page contient une liste de téléchargeables fournis par différents "
"modules"

#: templates/uds/index.html:70 templates/uds/html5/index.html:106
msgid "Java not found"
msgstr "Java non trouvé"

#: templates/uds/index.html:71 templates/uds/html5/index.html:109
msgid ""
"Java is not available on your browser, and the selected transport needs it."
msgstr ""
"Java n'est pas disponible sur votre navigateur, et le transport sélectionné "
"en a besoin."

#: templates/uds/index.html:72 templates/uds/html5/index.html:110
msgid "Please, install latest version from"
msgstr "Veuillez installer une version plus récente de"

#: templates/uds/index.html:72 templates/uds/html5/index.html:110
msgid "Java website"
msgstr "Site Web Java"

#: templates/uds/index.html:72 templates/uds/html5/index.html:110
msgid "and restart browser"
msgstr "Redémarrez le navigateur"

#: templates/uds/index.html:78 templates/uds/html5/index.html:126
msgid "Ip"
msgstr "IP"

#: templates/uds/index.html:80 templates/uds/html5/index.html:128
msgid "Transports"
msgstr "Transports"

#: templates/uds/internal_page.html:34 templates/uds/prefs.html:12
#: templates/uds/html5/snippets/navbar.html:39
msgid "Preferences"
msgstr "Préférences"

#: templates/uds/internal_page.html:40
msgid "Log out"
msgstr "Déconnexion"

#: templates/uds/login.html:6
msgid "Login to UDS"
msgstr "Connexion à UDS"

#: templates/uds/login.html:78
msgid "Login"
msgstr "Login"

#: templates/uds/login.html:83
msgid "Login data"
msgstr "Données de connexion"

#: templates/uds/login.html:86
msgid "Enter"
msgstr "Entrez"

#: templates/uds/login.html:93 templates/uds/html5/login.html:94
msgid "Back to login"
msgstr "Retour à la connexion"

#: templates/uds/prefs.html:6 templates/uds/html5/prefs.html:5
msgid "UDS User Preferences"
msgstr "Préférences de l'utilisateur UDS"

#: templates/uds/prefs.html:16 templates/uds/html5/prefs.html:12
msgid "Save Preferences"
msgstr "Enregistrer les préférences"

#: templates/uds/admin/snippets/navbar.html:6
#: templates/uds/html5/snippets/navbar.html:6
msgid "toggle navigation"
msgstr "activer/désactiver navigation"

#: templates/uds/admin/snippets/navbar.html:18
msgid "Service providers"
msgstr "Fournisseurs de services"

#: templates/uds/admin/snippets/navbar.html:19
#: templates/uds/admin/tmpl/authenticators.html:4
msgid "Authenticators"
msgstr "Authentificateurs"

#: templates/uds/admin/snippets/navbar.html:21
#: templates/uds/admin/tmpl/connectivity.html:4
msgid "Connectivity"
msgstr "Connectivité"

#: templates/uds/admin/snippets/navbar.html:22
msgid "Deployed services"
msgstr "Services déployés"

#: templates/uds/admin/snippets/navbar.html:26
msgid "Configuration"
msgstr "Configuration"

#: templates/uds/admin/snippets/navbar.html:57
msgid "Exit dashboard"
msgstr "Tableau de bord de sortie"

#: templates/uds/admin/snippets/navbar.html:58
#: templates/uds/html5/snippets/navbar.html:47
msgid "logout"
msgstr "logout"

#: templates/uds/admin/tmpl/authenticators.html:4
msgid "administration of authenticators"
msgstr "administration des authentificateurs"

#: templates/uds/admin/tmpl/connectivity.html:4
#: templates/uds/admin/tmpl/dashboard.html:4
msgid "overview"
msgstr "vue d'ensemble"

#: templates/uds/html5/detectJava.html:4
msgid "Login redirection to UDS"
msgstr "Redirection de connexion à l'UDS"

#: templates/uds/html5/error.html:12
msgid "An error occurred"
msgstr "Une erreur s'est produite"

#: templates/uds/html5/error.html:16
#: templates/uds/html5/show_transport.html:10
#: templates/uds/snippets/back_to_list.html:3
msgid "Back to services list"
msgstr "Retour à la liste de services"

#: templates/uds/html5/index.html:4
msgid "Available services list"
msgstr "Liste des services disponibles"

#: templates/uds/html5/index.html:83
msgid "transports"
msgstr "Transports"

#: templates/uds/html5/index.html:123
msgid "Administrator info panel"
msgstr "Panneau info administrateur"

#: templates/uds/html5/index.html:129
msgid "User Agent"
msgstr "User Agent"

#: templates/uds/html5/index.html:130
msgid "OS"
msgstr "SYSTÈME D'EXPLOITATION"

#: templates/uds/html5/login.html:4 templates/uds/html5/login.html.py:69
msgid "Welcome to UDS"
msgstr "Bienvenue à l'UDS"

#: templates/uds/html5/login.html:76
msgid "invalid credentials"
msgstr "informations d'identification non valides"

#: templates/uds/html5/login.html:84
msgid "username"
msgstr "nom d'utilisateur"

#: templates/uds/html5/login.html:85
msgid "password"
msgstr "mot de passe"

#: templates/uds/html5/login.html:88
msgid "Sign in"
msgstr "Connexion"

#: templates/uds/html5/prefs.html:11
msgid "Cancel"
msgstr "Annuler"

#: templates/uds/html5/service_not_ready.html:4
#: templates/uds/html5/service_not_ready.html:12
msgid "The service is not ready"
msgstr "Le service n'est pas prêt"

#: templates/uds/html5/service_not_ready.html:14
msgid ""
"The service is not ready at this moment. Please, try it again after a few "
"seconds."
msgstr ""
"Le service n'est pas prêt à ce moment. S'il vous plaît, essayez à nouveau "
"après quelques secondes."

#: templates/uds/html5/service_not_ready.html:15
msgid ""
"The service you has requested was not ready, and is being created right now. "
"It will be availabe shortly"
msgstr ""
"Le service que vous a demandé n'était pas prêt et il est créé dès "
"maintenant. Il sera disponible sous peu"

#: templates/uds/html5/service_not_ready.html:17
msgid "Back"
msgstr "Précédent"

#: templates/uds/html5/snippets/navbar.html:20
msgid "About"
msgstr "Sur"

#: templates/uds/html5/snippets/navbar.html:44
msgid "Dashboard"
msgstr "Tableau de bord"

#: templates/uds/html5/templates/base.html:52
msgid ""
"Your browser is supported only partially. Please, upgrade it to a modern "
"html5 browser like Firefox, Chrome, Opera, ... (IE must be 10 or better)"
msgstr ""
"Votre navigateur est pris en charge que partiellement. S'il vous plaît, "
"mettre à jour à un moderne HTML5 navigateur tel que Firefox, Chrome, "
"Opera... (IE doit être de 10 ou mieux)"

#: templates/uds/snippets/admin_user.html:4
msgid "Admin"
msgstr "Admin"

#: templates/uds/snippets/lang.html:9
msgid "Language"
msgstr "Langue"

#: transports/HTML5RDP/HTML5RDP.py:55
msgid "HTML5 RDP Transport"
msgstr "HTML5 RDP Transport"

#: transports/HTML5RDP/HTML5RDP.py:57
msgid "RDP Transport using HTML5 client"
msgstr "RDP Transport utilisant HTML5 client"

#: transports/HTML5RDP/HTML5RDP.py:62
msgid "Tunnel Server"
msgstr "Serveur de tunnel"

#: transports/HTML5RDP/HTML5RDP.py:62
msgid ""
"Host of the tunnel server (use http/https & port if needed) as accesible "
"from users"
msgstr ""
"Accessible l'hôte du serveur tunnel (utiliser le protocole http/https & port "
"si nécessaire) des utilisateurs"

#: transports/HTML5RDP/HTML5RDP.py:63 transports/NX/NXTransport.py:60
#: transports/NX/TSNXTransport.py:65 transports/RDP/RDPTransport.py:58
#: transports/RDP/TSRDPTransport.py:62
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "Empty creds"
msgstr "Références vide"

#: transports/HTML5RDP/HTML5RDP.py:63 transports/NX/NXTransport.py:60
#: transports/NX/TSNXTransport.py:65 transports/RDP/RDPTransport.py:58
#: transports/RDP/TSRDPTransport.py:62
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "If checked, the credentials used to connect will be emtpy"
msgstr ""
"Si coché, les informations d'identification utilisées pour se connecter sera "
"vide"

#: transports/HTML5RDP/HTML5RDP.py:64 transports/NX/NXTransport.py:61
#: transports/NX/TSNXTransport.py:66 transports/RDP/RDPTransport.py:59
#: transports/RDP/TSRDPTransport.py:63
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66
msgid "If not empty, this username will be always used as credential"
msgstr ""
"Si ce n'est vide, ce nom d'utilisateur sera toujours utilisé comme des "
"titres de compétences"

#: transports/HTML5RDP/HTML5RDP.py:65 transports/NX/NXTransport.py:62
#: transports/NX/TSNXTransport.py:67 transports/RDP/RDPTransport.py:60
#: transports/RDP/TSRDPTransport.py:64
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67
msgid "If not empty, this password will be always used as credential"
msgstr ""
"Si ce n'est vide, ce mot de passe sera toujours utilisé comme des titres de "
"compétences"

#: transports/HTML5RDP/HTML5RDP.py:66 transports/RDP/RDPTransport.py:61
#: transports/RDP/TSRDPTransport.py:65
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid ""
"If not empty, this domain will be always used as credential (used as DOMAIN"
"\\user)"
msgstr ""
"Si ce n'est vide, ce domaine sera toujours utilisé comme des titres de "
"compétences (utilisé comme domaine\\User)"

#: transports/HTML5RDP/HTML5RDP.py:67
msgid "Enable Audio"
msgstr "Activez l'Audio"

#: transports/HTML5RDP/HTML5RDP.py:67
msgid ""
"If checked, the audio will be redirected to client (if client browser "
"supports it)"
msgstr ""
"Si coché, le son sera redirigé vers le client (si navigateur client Il prend "
"en charge)"

#: transports/HTML5RDP/HTML5RDP.py:68
msgid "Enable Printing"
msgstr "Activer l'impression"

#: transports/HTML5RDP/HTML5RDP.py:68
msgid ""
"If checked, the printing will be redirected to client (if client browser "
"supports it)"
msgstr ""
"S'il est activé, l'impression sera redirigée vers le client (si navigateur "
"client Il prend en charge)"

#: transports/HTML5RDP/HTML5RDP.py:74
msgid "The server must be http or https"
msgstr "Der Server muss http oder Https sein."

#: transports/HTML5RDP/HTML5RDP.py:152
msgid "Launching HTML5 RDP connection"
msgstr "Lancer la connexion RDP HTML5"

#: transports/NX/NXTransport.py:54
msgid "NX Transport (direct)"
msgstr "NX Transport (direct)"

#: transports/NX/NXTransport.py:56
msgid "NX Transport for direct connection"
msgstr "NX Transport pour une connexion directe"

#: transports/NX/NXTransport.py:63 transports/NX/TSNXTransport.py:68
#: transports/TSNX/TSNXTransport.py:68
msgid "Listen port"
msgstr "Écouter le port"

#: transports/NX/NXTransport.py:63 transports/NX/TSNXTransport.py:68
#: transports/TSNX/TSNXTransport.py:68
msgid "Listening port of NX (ssh) at client machine"
msgstr "Écoute le port de NX (ssh) à la machine client"

#: transports/NX/NXTransport.py:64 transports/NX/TSNXTransport.py:69
#: transports/TSNX/TSNXTransport.py:69
msgid "Connection"
msgstr "Connexion"

#: transports/NX/NXTransport.py:64 transports/NX/TSNXTransport.py:69
#: transports/TSNX/TSNXTransport.py:69
msgid "Connection speed for this transport (quality)"
msgstr "Vitesse de connexion pour ce transport (qualité)"

#: transports/NX/NXTransport.py:71 transports/NX/TSNXTransport.py:76
#: transports/TSNX/TSNXTransport.py:76
msgid "Session"
msgstr "Session"

#: transports/NX/NXTransport.py:71 transports/NX/TSNXTransport.py:76
#: transports/TSNX/TSNXTransport.py:76
msgid "Desktop session"
msgstr "Session de bureau"

#: transports/NX/NXTransport.py:76 transports/NX/TSNXTransport.py:81
#: transports/TSNX/TSNXTransport.py:81
msgid "Disk Cache"
msgstr "Cache disque"

#: transports/NX/NXTransport.py:76 transports/NX/TSNXTransport.py:81
#: transports/TSNX/TSNXTransport.py:81
msgid "Cache size en Mb stored at disk"
msgstr "Cache en taille que Mo stocké à disque"

#: transports/NX/NXTransport.py:84 transports/NX/TSNXTransport.py:89
#: transports/TSNX/TSNXTransport.py:89
msgid "Memory Cache"
msgstr "Mémoire Cache"

#: transports/NX/NXTransport.py:84 transports/NX/TSNXTransport.py:89
#: transports/TSNX/TSNXTransport.py:89
msgid "Cache size en Mb keept at memory"
msgstr "Taille en Mb montagne à la mémoire de cache."

#: transports/NX/TSNXTransport.py:55 transports/TSNX/TSNXTransport.py:55
msgid "NX Transport (tunneled)"
msgstr "Transport NX (tunnel)"

#: transports/NX/TSNXTransport.py:57 transports/TSNX/TSNXTransport.py:57
msgid "NX Transport for tunneled connection"
msgstr "Transport NX pour connexion tunnelée"

#: transports/NX/TSNXTransport.py:62 transports/RDP/TSRDPTransport.py:59
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid "Tunnel server"
msgstr "Serveur de tunnel"

#: transports/NX/TSNXTransport.py:62 transports/RDP/TSRDPTransport.py:59
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid ""
"IP or Hostname of tunnel server send to client device (\"public\" ip) and "
"port. (use HOST:PORT format)"
msgstr ""
"IP ou nom d'hôte du serveur de tunnel envoyer à la machine cliente (« public "
"» ip) et port. (utilisez le format de l'hôte : PORT)"

#: transports/NX/TSNXTransport.py:63 transports/RDP/TSRDPTransport.py:60
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid "Tunnel host check"
msgstr "Tunnel hôte cocher"

#: transports/NX/TSNXTransport.py:63 transports/RDP/TSRDPTransport.py:60
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid ""
"If not empty, this server will be used to check if service is running before "
"assigning it to user. (use HOST:PORT format)"
msgstr ""
"Si ce n'est vide, ce serveur sera utilisé pour vérifier si le service "
"s'exécute avant assignant à l'utilisateur. (utilisez le format de l'hôte : "
"PORT)"

#: transports/NX/TSNXTransport.py:103 transports/RDP/TSRDPTransport.py:75
#: transports/RGS-enterprise/TRGSTransport.py:71
#: transports/TSNX/TSNXTransport.py:103
msgid "Must use HOST:PORT in Tunnel Server Field"
msgstr "Devez utiliser HOST : PORT dans le champ serveur Tunnel"

#: transports/NX/__init__.py:45 transports/TSNX/__init__.py:44
msgid "NX Protocol"
msgstr "Protocole de NX"

#: transports/NX/__init__.py:51
msgid "UDS Actor connector for NX <b>(requires nomachine packages)</b>"
msgstr "Connecteur UDS acteur pour NX <b>(nécessite nomachine packages)</b>"

#: transports/NX/web.py:78 transports/TSNX/web.py:79
msgid ""
"In order to use this transport, you need to install first OpenNX Client for "
"mac"
msgstr ""
"Pour utiliser ce type de transport, vous devez installer le premier OpenNX "
"Client pour Mac"

#: transports/NX/web.py:79 transports/TSNX/web.py:80
msgid "You can oibtain it from "
msgstr "Vous pouvez oibtain de "

#: transports/NX/web.py:79 transports/TSNX/web.py:80
msgid "OpenNx Website"
msgstr "OpenNx site Web"

#: transports/NX/web.py:81 transports/TSNX/web.py:82
msgid ""
"In order to use this transport, you need to install first Nomachine Nx "
"Client version 3.5.x"
msgstr ""
"Afin d'utiliser ce transport, vous devez installer le premier Nomachine Nx "
"Client version 3.5.x"

#: transports/NX/web.py:82 transports/TSNX/web.py:83
msgid "you can obtain it for your platform from"
msgstr "vous pouvez l'obtenir pour votre plate-forme de"

#: transports/NX/web.py:82 transports/TSNX/web.py:83
msgid "nochamine web site"
msgstr "site web de nochamine"

#: transports/RDP/RDPTransport.py:52
msgid "RDP Transport (direct)"
msgstr "Transport de RDP (direct)"

#: transports/RDP/RDPTransport.py:54
msgid "RDP Transport for direct connection"
msgstr "Transport de RDP pour une connexion directe"

#: transports/RDP/RDPTransport.py:62 transports/RDP/TSRDPTransport.py:66
msgid "Allow Smartcards"
msgstr "Permettre aux cartes à puce"

#: transports/RDP/RDPTransport.py:62 transports/RDP/TSRDPTransport.py:66
msgid "If checked, this transport will allow the use of smartcards"
msgstr "Si cochée, ce transport permettra l'utilisation de cartes à puce"

#: transports/RDP/RDPTransport.py:63 transports/RDP/TSRDPTransport.py:67
msgid "Allow Printers"
msgstr "Permettre aux imprimantes"

#: transports/RDP/RDPTransport.py:63 transports/RDP/TSRDPTransport.py:67
msgid "If checked, this transport will allow the use of user printers"
msgstr ""
"Si cochée, ce transport permettra l'utilisation des imprimantes utilisateur"

#: transports/RDP/RDPTransport.py:64 transports/RDP/TSRDPTransport.py:68
msgid "Allow Drives"
msgstr "Permettre aux lecteurs"

#: transports/RDP/RDPTransport.py:64 transports/RDP/TSRDPTransport.py:68
msgid "If checked, this transport will allow the use of user drives"
msgstr ""
"Si cochée, ce transport permettra l'utilisation des lecteurs de l'utilisateur"

#: transports/RDP/RDPTransport.py:65 transports/RDP/TSRDPTransport.py:69
msgid "Allow Serials"
msgstr "Permettre aux publications en série"

#: transports/RDP/RDPTransport.py:65 transports/RDP/TSRDPTransport.py:69
msgid "If checked, this transport will allow the use of user serial ports"
msgstr ""
"Si cochée, ce transport permettra l'utilisation de l'utilisateur ports série"

#: transports/RDP/TSRDPTransport.py:53
msgid "RDP Transport (tunneled)"
msgstr "Transport de RDP (tunnel)"

#: transports/RDP/TSRDPTransport.py:55
msgid "RDP Transport for tunneled connection"
msgstr "Transport de RDP de connexion tunnelée"

#: transports/RDP/__init__.py:39
msgid "Remote Desktop Protocol"
msgstr "Protocole Bureau distant"

#: transports/RDP/web.py:84
msgid "In order to use this service, you should first install CoRD."
msgstr "Afin d'utiliser ce service, vous devez d'abord installer cordon."

#: transports/RDP/web.py:85 transports/RGS-enterprise/web.py:83
msgid "You can obtain it from"
msgstr "Vous pouvez l'obtenir de"

#: transports/RDP/web.py:85
msgid "CoRD Website"
msgstr "Site Web du cordon"

#: transports/RGS-enterprise/RGSTransport.py:34
msgid "RGS Transport (direct)"
msgstr "RGS Transport (direct)"

#: transports/RGS-enterprise/RGSTransport.py:36
msgid "RGS Transport for direct connection"
msgstr "RGS Transport pour une connexion directe"

#: transports/RGS-enterprise/RGSTransport.py:45
#: transports/RGS-enterprise/TRGSTransport.py:50
msgid "Image quality"
msgstr "Qualité d'image"

#: transports/RGS-enterprise/RGSTransport.py:46
#: transports/RGS-enterprise/TRGSTransport.py:51
msgid "Quality of image codec (0-100)"
msgstr "Qualité du codec d'image (0-100)"

#: transports/RGS-enterprise/RGSTransport.py:47
#: transports/RGS-enterprise/TRGSTransport.py:52
msgid "Adjustable Quality"
msgstr "Qualité réglable"

#: transports/RGS-enterprise/RGSTransport.py:48
#: transports/RGS-enterprise/TRGSTransport.py:53
msgid "If checked, the image quality will be adjustable with bandwidth"
msgstr "S'il est activé, la qualité d'image sera réglable avec bande passante"

#: transports/RGS-enterprise/RGSTransport.py:49
#: transports/RGS-enterprise/TRGSTransport.py:54
msgid "Min. Adjustable Quality"
msgstr "Qualité réglable min."

#: transports/RGS-enterprise/RGSTransport.py:50
#: transports/RGS-enterprise/TRGSTransport.py:55
msgid ""
"The lowest image quality applied to images to maintain the minimum update "
"rate."
msgstr ""
"La qualité d'image le plus bas appliquée aux images de maintenir la mise à jour minimale "
"Ravel"

#: transports/RGS-enterprise/RGSTransport.py:51
#: transports/RGS-enterprise/TRGSTransport.py:56
msgid "Adjustable Frame Rate"
msgstr "Cadence réglable"

#: transports/RGS-enterprise/RGSTransport.py:52
#: transports/RGS-enterprise/TRGSTransport.py:57
msgid "Update rate threshold to begin adjusting image quality"
msgstr "Seuil de taux de mise à jour pour commencer le réglage qualité de l'image"

#: transports/RGS-enterprise/RGSTransport.py:53
#: transports/RGS-enterprise/TRGSTransport.py:58
msgid "Match Local Resolution"
msgstr "Adapter la résolution locale"

#: transports/RGS-enterprise/RGSTransport.py:54
#: transports/RGS-enterprise/TRGSTransport.py:59
msgid ""
"Change the Sender's resolution to match the Receiver's resolution when "
"connecting"
msgstr ""
"Changer la résolution de l'expéditeur pour l'adapter résolution du récepteur lorsque "
"connexion"

#: transports/RGS-enterprise/RGSTransport.py:55
#: transports/RGS-enterprise/TRGSTransport.py:60
msgid "Redirect USB"
msgstr "Redirection USB"

#: transports/RGS-enterprise/RGSTransport.py:56
#: transports/RGS-enterprise/TRGSTransport.py:61
msgid "If checked, the USB will be redirected."
msgstr "Si cochée, l'USB sera redirigé."

#: transports/RGS-enterprise/RGSTransport.py:57
#: transports/RGS-enterprise/TRGSTransport.py:62
msgid "Redirect Audio"
msgstr "Redirection Audio"

#: transports/RGS-enterprise/RGSTransport.py:58
#: transports/RGS-enterprise/TRGSTransport.py:63
msgid "If checked, the Audio will be redirected."
msgstr "Si coché, le son sera redirigé."

#: transports/RGS-enterprise/RGSTransport.py:59
#: transports/RGS-enterprise/TRGSTransport.py:64
msgid "Redirect Mic"
msgstr "Redirection Mic"

#: transports/RGS-enterprise/RGSTransport.py:60
#: transports/RGS-enterprise/TRGSTransport.py:65
msgid "If checked, the Mic will be redirected."
msgstr "Si cochée, le micro sera redirigé."

#: transports/RGS-enterprise/TRGSTransport.py:36
msgid "RGS Transport (tunneled)"
msgstr "RGS Transport (tunnel)"

#: transports/RGS-enterprise/TRGSTransport.py:38
msgid "RGS Transport for tunneled connection"
msgstr "RGS Transport pour connexion par tunnel"

#: transports/RGS-enterprise/web.py:82
msgid "In order to use this service, you should first install RGS Receiver."
msgstr "Pour utiliser ce service, vous devez commencer par installer récepteur RGS."

#: transports/RGS-enterprise/web.py:83
msgid "HP Website"
msgstr "Site Web de HP"

#: web/errors.py:60
msgid "Unknown error"
msgstr "Erreur inconnue"

#: web/errors.py:63 xmlrpc/auths/AdminAuth.py:182
#: xmlrpc/auths/AdminAuth.py:188
msgid "Access denied"
msgstr "Accès refusé"

#: web/errors.py:64
msgid ""
"Invalid service. The service is not available at this moment. Please, try "
"later"
msgstr ""
"Service non valide. Le service n'est pas disponible en ce moment. SVP, "
"essayez plus tard"

#: web/errors.py:65
msgid "Maximum services limit reached. Please, contact administrator"
msgstr ""
"Limite de services maximale atteinte. Veuillez contacter administrateur"

#: web/errors.py:66
msgid "You need to enable cookies to let this application work"
msgstr "Vous devez activer les cookies de laisser cette application"

#: web/errors.py:67
msgid "User service not found"
msgstr "Service utilisateur introuvable"

#: web/errors.py:68
msgid "Authenticator not found"
msgstr "Authentificateur introuvable"

#: web/errors.py:69 xmlrpc/auths/AdminAuth.py:173
msgid "Invalid authenticator"
msgstr "Authentificateur non valide"

#: web/errors.py:70
msgid "Invalid request received"
msgstr "Requête non valide reçu"

#: web/errors.py:71
msgid ""
"Your browser is not supported. Please, upgrade it to a modern HTML5 browser "
"like Firefox or Chrome"
msgstr ""
"Votre navigateur n'est pas pris en charge. S'il vous plaît, mettre à niveau "
"vers un navigateur modern de HTML5 comme Firefox ou Chrome"

#: web/views.py:401
msgid "Authenticator do not provides information"
msgstr "Authentificateur ne fournit pas d'informations"

#: web/forms/LoginForm.py:50
msgid "Select authenticator"
msgstr "Sélectionnez authentificateur"

#: web/forms/LoginForm.py:54
msgid "authenticator"
msgstr "authentificateur"

#: web/forms/LoginForm.py:71
msgid "Authenticator"
msgstr "Authentificateur"

#: xmlrpc/auths/AdminAuth.py:115
msgid "Credentials no longer valid"
msgstr "Informations d'identification n'est plus valides"

#: xmlrpc/auths/AdminAuth.py:151
msgid "Administration"
msgstr "Administration"

#: xmlrpc/auths/Authenticators.py:107
msgid "Authenticator does not exists"
msgstr "Authentificateur n'existe pas"

#: xmlrpc/auths/Authenticators.py:163 xmlrpc/osmanagers/OSManagers.py:117
#: xmlrpc/services/ServiceProviders.py:115
#: xmlrpc/services/ServiceProviders.py:139 xmlrpc/services/Services.py:164
#: xmlrpc/services/Services.py:188 xmlrpc/transports/Networks.py:87
#: xmlrpc/transports/Networks.py:98
#, python-format
msgid "Name %s already exists"
msgstr "Nom %s existe déjà"

#: xmlrpc/auths/Authenticators.py:240
msgid "Authenticator do not supports search"
msgstr "Authenticateur ne soutient la recherche"

#: xmlrpc/auths/Authenticators.py:246
msgid "Specified authenticator do not exists anymore. Please, reload gui"
msgstr "Authentificateur spécifiée n'existe pas plus. Veuillez recharger gui"

#: xmlrpc/auths/Authenticators.py:250
msgid "BUG: Reached a point that should never have been reached!!!"
msgstr "BOGUE : Atteint un point qui devrait jamais été atteint!!!"

#: xmlrpc/log/logs.py:55 xmlrpc/services/DeployedServices.py:281
msgid "Deployed service does not exists"
msgstr "Service déployée n'existe pas"

#: xmlrpc/log/logs.py:64
msgid "User service does not exists"
msgstr "Il n'existe pas de service de l'utilisateur"

#: xmlrpc/osmanagers/OSManagers.py:131
msgid "This os mnager is being used by deployed services"
msgstr ""
"Ce gestionnaire de système d'exploitation est utilisé par les services de "
"déploiements"

#: xmlrpc/osmanagers/OSManagers.py:147
msgid "There is deployed services using this os manager"
msgstr ""
"Il y a des services déployées à l'aide de ce gestionnaire de système "
"d'exploitation"

#: xmlrpc/osmanagers/OSManagers.py:149
msgid "Can't find os manager"
msgstr "Impossible de trouver os gestionnaire"

#: xmlrpc/services/DeployedServices.py:52
msgid "Unknown"
msgstr "Inconnu"

#: xmlrpc/services/DeployedServices.py:112
#: xmlrpc/services/DeployedServices.py:176
#: xmlrpc/services/DeployedServices.py:195
#: xmlrpc/services/DeployedServices.py:211
#: xmlrpc/services/DeployedServices.py:225
#: xmlrpc/services/DeployedServices.py:252
#: xmlrpc/services/DeployedServices.py:266
msgid "Deployed Service does not exists"
msgstr "Service déployée n'existe pas"

#: xmlrpc/services/DeployedServices.py:209
msgid "Group does not exists"
msgstr "Groupe n'existe pas"

#: xmlrpc/services/DeployedServices.py:237
msgid "Can't find deployed service"
msgstr "Impossible de trouver le service déployé"

#: xmlrpc/services/DeployedServices.py:250
msgid "Transport does not exists"
msgstr "Transport n'existe pas"

#: xmlrpc/services/ServiceProviders.py:154
msgid "Can't delete service provider with services associated"
msgstr ""
"Impossible de supprimer le fournisseur de service avec services associés"

#: xmlrpc/services/ServiceProviders.py:157
msgid "Can't locate the service provider"
msgstr "Impossible de trouver le fournisseur de services"

#: xmlrpc/services/ServiceProviders.py:157 xmlrpc/services/Services.py:206
#: xmlrpc/transports/Networks.py:71 xmlrpc/transports/Networks.py:79
#: xmlrpc/transports/Networks.py:96
msgid "Please, refresh interface"
msgstr "Veuillez actualiser interface"

#: xmlrpc/services/Services.py:203
msgid "Can't delete services with deployed services associated"
msgstr "Impossible de supprimer les services avec des services déployés liés"

#: xmlrpc/services/Services.py:206
msgid "Can't locate the service"
msgstr "Impossible de localiser le service"

#: xmlrpc/services/UserDeployedServices.py:100
#: xmlrpc/services/UserDeployedServices.py:116
msgid "The deployed service is not active"
msgstr "Le service de déploiement n'est pas actif"

#: xmlrpc/services/UserDeployedServices.py:103
#: xmlrpc/services/UserDeployedServices.py:119
msgid "This service don't allows assignations"
msgstr "Ce service ne permet l'assignation"

#: xmlrpc/services/UserDeployedServices.py:108
#: xmlrpc/services/UserDeployedServices.py:126
msgid "Deployed service not found!!! (refresh interface)"
msgstr "Déployées service introuvable!!! (actualisation interface)"

#: xmlrpc/services/UserDeployedServices.py:128
msgid "User not found!!! (refresh interface)"
msgstr "Utilisateur introuvable!!! (actualisation interface)"

#: xmlrpc/services/UserDeployedServices.py:147
msgid "No error"
msgstr "Pas d'erreur"

#: xmlrpc/services/UserDeployedServices.py:153
#: xmlrpc/services/UserDeployedServices.py:178
msgid "User deployed service not found!!!"
msgstr "Service de l'utilisateur ne se trouve pas déployée!!!"

#: xmlrpc/stats/stats.py:75
msgid "Service does not exists"
msgstr "Il n'existe pas de service"

#: xmlrpc/transports/Networks.py:71
msgid "Can't locate the transport"
msgstr "Impossible de localiser le transport"

#: xmlrpc/transports/Networks.py:79 xmlrpc/transports/Networks.py:96
msgid "Can't locate the network"
msgstr "Impossible de localiser le réseau"
